[snowflake]
account = "ETLXDPW-SB05598"
user = "" # e.g. TTESTERSON@MONTROSE-ENV.COM
password = ""
role = "TRAINING_{USER}_ADMIN" # e.g. TRAINING_TTESTERSON_ADMIN
warehouse = "CTEH_DATA_WH"
database = "TRAINING_{USER}_DB" # e.g. TRAINING_TTESTERSON_DB
schema = "RAW"